SELECT flat.guid,
  flat.subspecies,
  CAST(flat.cat_num AS INTEGER) AS catalognumberint,
  flat.collectors,
  state_prov,
  county,
  flat.spec_locality,
  collectornumber,
  began_date,
  ended_date,
  parts,
  sex,
  dec_lat,
  dec_long,
  coordinateuncertaintyinmeters,
  attributedetail
FROM flat
WHERE guid_prefix LIKE 'MVZ:Mamm'
  AND species LIKE 'Sorex vagrans'
  AND country IN ('United States',
                  'Mexico',
                  'Canada',
                  'NULL')
  AND state_prov IN ('Alaska',
                    'Alberta',
                    'Arizona',
                    'Arkansas',
                    'British Columbia',
                    'California',
                    'Colorado',
                    'Idaho',
                    'Illinois',
                    'Kansas',
                    'Mexico',
                    'Michigan',
                    'Montana',
                    'Nebraska',
                    'New Mexico',
                    'North Dakota',
                    'Nevada',
                    'Oregon',
                    'Saskatchewan',
                    'South Dakota',
                    'Texas',
                    'Utah',
                    'Washington',
                    'Wyoming',
                    'Aguascalientes',
                    'Baja California',
                    'Baja California Sur',
                    'Campeche',
                    'Chiapas',
                    'Chihuahua',
                    'Coahuila',
                    'Colima',
                    'Durango',
                    'Guanajuato',
                    'Guerrero',
                    'Hidalgo',
                    'Jalisco',
                    'México',
                    'Mexico',
                    'México City',
                    'Mexico City',
                    'Michoacán',
                    'Michoacan',
                    'Morelos',
                    'Nayarit',
                    'Nuevo León',
                    'Nuevo Leon',
                    'Oaxaca',
                    'Puebla',
                    'Querétaro',
                    'Queretaro',
                    'Quintana Roo',
                    'Sinaloa',
                    'Sonora',
                    'San Luis Potosi',
                    'Tamaulipas',
                    'Tlaxcala',
                    'Veracruz',
                    'Yucatán',
                    'Yucatan',
                    'Zacatecas')